### ISSUE TITLE
Plugin Functionality?

### ISSUE THREAD

**Issue by rcoletti116** [homebridge-plugins/homebridge-resideo#160]
I have a Honeywell T5 that has native HomeKit support. I installed this plugin and get a duplicate thermostat. I'm just curious what functionality this plugin provides for thermostats that already support HomeKit. It looks like most of the Thermostats this supports have native HomeKit support already. Sorry if this has been asked before. I couldn't find an answer.

**Comment by donavanbecker** [comment]
@rcoletti116 This plugin was mainly created for the T9 thermostat which was promised HomeKit last year, and still doesn’t have it. I have seen a few people do what you are doing with it (duplicating existing thermostat).

**Comment by donavanbecker** [comment]
@rcoletti116: `v7.0.1` should take care of all the issues, if not I need a new issue filled out so I can look into it further. Please follow issue template so that I can get all the details I need. When posting logs, debug mode will be needs to look into further issues.
