### ISSUE TITLE
Does this support the T10 as well?

### ISSUE THREAD

**Issue by adammiarka** [homebridge-plugins/homebridge-resideo#162]
Does this integration also support the T10 thermostat.  Would be very similar to the T9, but Honeywell's pro model.   Need the T10 to control whole home humidifier.

**Comment by donavanbecker** [comment]
I believe the T10 uses the Honeywell Home app, so it should work with the T10 thermostat!

**Comment by adammiarka** [comment]
It does use the same Honeywell Home app.   Thanks!

**Comment by donavanbecker** [comment]
@adammiarka: `v7.0.1` should take care of all the issues, if not I need a new issue filled out so I can look into it further. Please follow issue template so that I can get all the details I need. When posting logs, debug mode will be needs to look into further issues.
