### ISSUE TITLE
Failed to update status of ******* Request failed with status code 401

### ISSUE THREAD

**Issue by MaverickC2** [homebridge-plugins/homebridge-resideo#194]
Upgraded to v6.1.0 and everything was working for a few hours now I see a lot of code 401 errors:

[7/30/2020, 15:44:07] [HoneywellHome] Failed to update status of Downstairs Request failed with status code 401
[7/30/2020, 15:44:07] [HoneywellHome] Failed to update status of Downstairs Request failed with status code 401
[7/30/2020, 15:44:07] [HoneywellHome] Failed to update status of Downstairs Request failed with status code 401

**Comment by donavanbecker** [comment]
is your thermostat still working with updates from HomeKit?

**Comment by MaverickC2** [comment]
It looks like the thermostat is updating but the 4 sensors I have stopped updating. They show incorrect temperatures.

**Comment by donavanbecker** [comment]
> It looks like the thermostat is updating but the 4 sensors I have stopped updating. They show incorrect temperatures.

Can you feel out the issue template? so I can have more info about your setup?

**Comment by donavanbecker** [comment]
@MaverickC2: `v7.0.1` should take care of all the issues, if not I need a new issue filled out so I can look into it further. Please follow issue template so that I can get all the details I need. When posting logs, debug mode will be needs to look into further issues.
