### ISSUE TITLE
Failed to refresh access token. device.groups is not iterable

### ISSUE THREAD

**Issue by CreeT6** [homebridge-plugins/homebridge-resideo#196]
[8/4/2020, 10:37:38 PM] [HoneywellHome] Got access token: xx
[8/4/2020, 10:37:38 PM] [HoneywellHome] New refresh token: xx
[8/4/2020, 10:37:38 PM] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[8/4/2020, 10:37:39 PM] [HoneywellHome] # of Locations Found: 1.
[8/4/2020, 10:37:39 PM] [HoneywellHome] Getting devices for xx...
[8/4/2020, 10:37:39 PM] [HoneywellHome] Failed to refresh access token. device.groups is not iterable

not sure what this means
linked account a few times, created another app, same error. lyric t5. homebridge running on windows10.

**Comment by CreeT6** [comment]
Could not discover devices. Request failed with status code 400

this error just showed up with the other one

**Comment by macjbraun** [comment]
Same here. I have 3 T5s. Only 2 show up. All 3 show in the Honeywell app, including In the connected services. The home app does not detect the third one. Also get this message. # of Locations Found: 2.

**Comment by macjbraun** [comment]
Update. I reset the missing thermostat homekit setup and now it shows up in the home app. The plug-in still reports the same as above, only finding 2 of the 3 thermostats.

**Comment by donavanbecker** [comment]
Since issue template wasn't used, I really have no details to go off of to even look into this. I am closing, please re open new issue and follow issue templates so that I have more details to look into that. Thanks!

**Comment by donavanbecker** [comment]
@macjbraun, @CreeT6: `v7.0.1` should take care of all the issues, if not I need a new issue filled out so I can look into it further. Please follow issue template so that I can get all the details I need. When posting logs, debug mode will be needs to look into further issues.
