### ISSUE TITLE
CurrentHeatingCoolingState not Updating

### ISSUE THREAD

**Issue by ericingravity** [homebridge-plugins/homebridge-resideo#238]
**Describe The Bug:**
The status of the thermostats show they are actively cooling even though the system isn't running. Home app shows in the status: 'Downstairs. 68º. Cooling.' The tile icon shows '(68º) Downstairs ... Cooling to 72º'. The tile icon is also white, indicating it is on. When I check the status in the Honeywell Home app, it does not show the equipment running.

**To Reproduce:**
1. Install and set up homebridge-honeywell-home
2. View thermostats in Home app
3. Adjust temperature up or down to start and stop equipment.
4. Visually compare Home app thermostat status to Honeywell thermostat status. Additionally, physically check equipment to see if it is running.

**Expected behavior:**
When equipment **isn't** running, the tile icon should be dark and just display the current temperature of the room, with no status such as 'Cooling...'. When equipment **is** running, tile icon should be white, the current temperature displayed in a color circle indicating which mode it is in (for example, blue for cool, red for heat), with status texting such as 'Cooling to...'.

**Logs:**
```
[9/10/2020, 06:38:23] Homebridge is running on port 51724.
[9/10/2020, 06:38:23] [HoneywellHome] Got access token: <removed>
[9/10/2020, 06:38:23] [HoneywellHome] New refresh token: <removed>
[9/10/2020, 06:38:23] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[9/10/2020, 06:38:24] [HoneywellHome] # of Locations Found: 1.
[9/10/2020, 06:38:24] [HoneywellHome] Getting devices for Home...
[9/10/2020, 06:38:24] [HoneywellHome] Restoring existing accessory from cache: Downstairs Thermostat
[9/10/2020, 06:38:25] [HoneywellHome] Restoring existing accessory from cache: Upstairs Thermostat
[9/10/2020, 06:38:42] [HoneywellHome] Sending request to Honeywell API. mode: Cool, coolSetpoint: 70, heatSetpoint: 62
[9/10/2020, 06:40:15] [HoneywellHome] Sending request to Honeywell API. mode: Cool, coolSetpoint: 70, heatSetpoint: 62
[9/10/2020, 06:43:39] [HoneywellHome] Sending request to Honeywell API. mode: Cool, coolSetpoint: 70, heatSetpoint: 62
[9/10/2020, 06:43:41] [HoneywellHome] Sending request to Honeywell API. mode: Cool, coolSetpoint: 71, heatSetpoint: 62
[9/10/2020, 06:45:02] [HoneywellHome] Sending request to Honeywell API. mode: Cool, coolSetpoint: 71, heatSetpoint: 62
[9/10/2020, 06:48:25] [HoneywellHome] Got access token: <removed>
[9/10/2020, 06:48:25] [HoneywellHome] New refresh token: <removed>
[9/10/2020, 06:48:25] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
[9/10/2020, 06:57:00] [HoneywellHome] Sending request to Honeywell API. mode: Cool, coolSetpoint: 72, heatSetpoint: 62
[9/10/2020, 06:57:13] [HoneywellHome] Sending request to Honeywell API. mode: Cool, coolSetpoint: 72, heatSetpoint: 68
[9/10/2020, 06:58:25] [HoneywellHome] Failed to update status of Upstairs Request failed with status code 401
[9/10/2020, 06:58:25] [HoneywellHome] Got access token: <removed>
[9/10/2020, 06:58:25] [HoneywellHome] New refresh token: <removed>
[9/10/2020, 06:58:25] [HoneywellHome] Homebridge config.json has been updated with new refresh token.
```

**Homebridge Config:**
```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "removed",
        "port": 51724,
        "pin": "removed"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "HoneywellHome",
            "credentials": {
                "consumerKey": "removed",
                "consumerSecret": "removed",
                "refreshToken": "removed",
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "ttl": 60,
                "thermostat": {
                    "hide_fan": true
                }
            },
            "platform": "HoneywellHome"
        }
    ]
}
```

**Screenshots:**
* [Honeywell app showing no equipment running](https://user-images.githubusercontent.com/26295329/92688643-508b9d80-f303-11ea-86da-f6d88c0b8b3b.jpg)
* [Honeywell app showing equipment running](https://user-images.githubusercontent.com/26295329/92688651-53868e00-f303-11ea-9f02-245476fa9dcb.jpg)
* [How Home app appears when no equipment is running](https://user-images.githubusercontent.com/26295329/92688656-55505180-f303-11ea-89b5-775f3728882f.jpg)

**Thermostat Model:**
(Two count) T10 Pros

# **Environment:**

* **Node.js Version**: v12.18.3
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.1.6
* **Homebridge Honeywell Home Version**: 7.0.1
* **Homebridge Config UI X Plugin Version**: 4.27.1
* **Operating System**: "Raspbian GNU/Linux 10 (buster)

**Comment by donavanbecker** [comment]
@ericingravity, thanks for reporting this. Can you put homebridge in debug mode. And post the what logs here? I believe it will be the same info as the T9, but want to make sure. These logs will show me more info about your thermostat from Honeywell.

**Comment by ericingravity** [comment]
Let me know if this log ([homebridge.log](https://github.com/donavanbecker/homebridge-honeywell-home/files/5205271/homebridge.log)) has the information you're looking for. Cheers.

**Comment by donavanbecker** [comment]
@ericingravity  okay can you give the new beta a try and report back? `v7.2.2-beta.6`

**Comment by ericingravity** [comment]
Same results. See this [new log](https://github.com/donavanbecker/homebridge-honeywell-home/files/5212084/homebridge2.log). After installing the beta, there are two additional thermostats listed. I tried removing cachedAccessories and restarting, but they persist. I reverted back to latest and they still persist. I'll try removing plugin and installing again a bit later.

**Comment by donavanbecker** [comment]
> Same results. See this [new log](https://github.com/donavanbecker/homebridge-honeywell-home/files/5212084/homebridge2.log). After installing the beta, there are two additional thermostats listed. I tried removing cachedAccessories and restarting, but they persist. I reverted back to latest and they still persist. I'll try removing plugin and installing again a bit later.

How did you clear your cachedAccessories? Did you do it through config ui x?

**Comment by donavanbecker** [comment]
@ericingravity,can you give the latest beta a try and report back? `v7.2.2-beta.12`

**Comment by ericingravity** [comment]
> How did you clear your cachedAccessories? Did you do it through config ui x?

I didn't know I could do it through there. I haven't used the UI much, but I see the option now. I just removed the cachedAccessories file in terminal.

> can you give the latest beta a try and report back?

Same results here still. Updated log [here](https://github.com/donavanbecker/homebridge-honeywell-home/files/5215240/homebridge3.log). (@leemcx)

**Comment by donavanbecker** [comment]
```
  "changeableValues": {
    "mode": "Cool",
    "autoChangeoverActive": false,
    "heatSetpoint": 62,
    "coolSetpoint": 78,
    "thermostatSetpointStatus": "PermanentHold",
    "heatCoolMode": "Cool"
  },
  "operationStatus": {
    "mode": "EquipmentOff",
    "fanRequest": false,
    "circulationFanRequest": false
  },
```
and then
```
  "changeableValues": {
    "mode": "Cool",
    "autoChangeoverActive": false,
    "heatSetpoint": 70,
    "coolSetpoint": 72,
    "thermostatSetpointStatus": "PermanentHold",
    "heatCoolMode": "Cool"
  },
  "operationStatus": {
    "mode": "Cool",
    "fanRequest": true,
    "circulationFanRequest": false
  },
```
From looking at your logs, it looks like the `operationStatus` is showing that it is off then cool mode. so maybe I should be pointing to `this.device.operationStatus.mode` instead of `this.device.changeableValues.heatCoolMode`

@ericingravity, @leemcx  Thoughts?

**Comment by donavanbecker** [comment]
> From looking at your logs, it looks like the `operationStatus` is showing that it is off then cool mode. so maybe I should be pointing to `this.device.operationStatus.mode` instead of `this.device.changeableValues.heatCoolMode`
> 
> 
> @ericingravity, @leemcx  Thoughts?


@ericingravity and @leemcx, I have pushed these changes in the latest beta. If you could test them out. I believe this is what we are looking for. `v7.2.2-beta.15`

To Install:
```
sudo npm install -g --unsafe-perm homebridge-honeywell-home@beta
```
To Revert:
```
sudo npm install -g --unsafe-perm homebridge-honeywell-home@latest
```

**Comment by donavanbecker** [comment]
@ericingravity and @leemcx, I can already confirm from testing that this is what we want. just wanna make sure that you are experiencing the same.

**Comment by ericingravity** [comment]
This is very close! It seems to get stuck in the 'Cooling' mode after it changes, though. [Video](https://github.com/donavanbecker/homebridge-honeywell-home/files/5225155/RPReplay_Final1600175227.MP4.zip) and corresponding [log](https://github.com/donavanbecker/homebridge-honeywell-home/files/5225166/homebridge4.log). You can see in this video the upstairs thermostat correctly showing 'Cool' instead of 'Cooling'.

I tried a few things before it got stuck in this state. I turned the equipment off (not Cool, Heat, or Auto). The icon did turn dark to indicate it was all the way off (not just the circle like in the video above, but the whole tile). I then turned it back on and set the temperature lower and it switched from 'Cool' status with a green circle to a 'Cooling' status with a blue circle. Once it got to this 'Cooling' status, it became stuck, even when changing it to 'Heat' ([video here](https://github.com/donavanbecker/homebridge-honeywell-home/files/5225176/RPReplay_Final1600175663.MP4.zip)).

**Comment by donavanbecker** [comment]
> This is very close! It seems to get stuck in the 'Cooling' mode after it changes, though. [Video](https://github.com/donavanbecker/homebridge-honeywell-home/files/5225155/RPReplay_Final1600175227.MP4.zip) and corresponding [log](https://github.com/donavanbecker/homebridge-honeywell-home/files/5225166/homebridge4.log). You can see in this video the upstairs thermostat correctly showing 'Cool' instead of 'Cooling'.
> 
> I tried a few things before it got stuck in this state. I turned the equipment off (not Cool, Heat, or Auto). The icon did turn dark to indicate it was all the way off (not just the circle like in the video above, but the whole tile). I then turned it back on and set the temperature lower and it switched from 'Cool' status with a green circle to a 'Cooling' status with a blue circle. Once it got to this 'Cooling' status, it became stuck, even when changing it to 'Heat' ([video here](https://github.com/donavanbecker/homebridge-honeywell-home/files/5225176/RPReplay_Final1600175663.MP4.zip)).

next beta should fix this. 

I used this right away:
```
    if (this.device.operationStatus.mode === 'Heat') {
      this.CurrentHeatingCoolingState = 1;
      this.platform.log.debug('Device is Currently: ', this.CurrentHeatingCoolingState);
    } else if (this.device.operationStatus.mode === 'Cool') {
      this.CurrentHeatingCoolingState = 2;
      this.platform.log.debug('Device is Currently: ', this.CurrentHeatingCoolingState);
    } else if (this.device.operationStatus.mode === 'Off')  {
      this.CurrentHeatingCoolingState = 0;
      this.platform.log.debug('Device is Currently: ', this.CurrentHeatingCoolingState);
    }
```
and switch to this.
```
    if (this.device.operationStatus.mode === 'Heat') {
      this.CurrentHeatingCoolingState = 1;
      this.platform.log.debug('Device is Currently: ', this.CurrentHeatingCoolingState);
    } else if (this.device.operationStatus.mode === 'Cool') {
      this.CurrentHeatingCoolingState = 2;
      this.platform.log.debug('Device is Currently: ', this.CurrentHeatingCoolingState);
    } else {
      this.CurrentHeatingCoolingState = 0;
      this.platform.log.debug('Device is Currently: ', this.CurrentHeatingCoolingState);
    }
```

New Version: `v7.2.2-beta.16`

**Comment by leemcx** [comment]
`v7.2.2-beta.16` has solved this issue for me. Thank you.

**Comment by ericingravity** [comment]
I just downloaded 7.2.2-beta.17 and all seems to be working. Thank you for your work!

**Comment by donavanbecker** [comment]
> I just downloaded 7.2.2-beta.17 and all seems to be working. Thank you for your work!

Awesome! Glad it is working for you both @ericgravity and @leemcx.

New homebridge has added some more changes that I need to finish. Right now if you are trying to hide the fan, etc.  it isn't working. but I will move that to #231.
