### ISSUE TITLE
I"m confused - which plugin?

### ISSUE THREAD

**Issue by jvmahon** [homebridge-plugins/homebridge-resideo#264]
I am a bit confused as to the difference between the two plugins:

- Homebridge-Honeywell-Home-Thermostat, and
- Homebridge-Honeywell-Home

Can a further description be added to the README or here to explain why there are the two?  

I have a Honeywell Redlink system, but it is generally compatible with plugins for their WiFi thermostats and anything that works on the TCC system, so I wanted to try these plugins, but from the README they look awfully similar. Thanks.

**Comment by donavanbecker** [comment]
homebridge-honeywell-home has ever plugin together, thermostats, room sensors, and leak sensors.

Homebridge-Honeywell-home-thermostat, only supports thermostats.

[Other Honeywell Plugins.](https://github.com/donavanbecker/homebridge-honeywell-home/wiki/Other-Plugins)

**Comment by jvmahon** [comment]
Thank you!

**Comment by donavanbecker** [comment]
> Thank you!

Let me know which one you try and if it works. I am curious, since I don't have all the models. Ha
