### ISSUE TITLE
HOOBS - not registered by any plugin

### ISSUE THREAD

**Issue by 00JohnD** [homebridge-plugins/homebridge-resideo#265]
Hello, I followed the instruction, and i get an error message on Hoobs launch:

_Loaded plugin "homebridge-honeywell-leak".
The requested platform "HoneywellLeak" was not registered by any plugin.
Your config.json is requesting the platform "HoneywellLeak" which has not been published by any installed plugins._

Can you please help?

**Comment by donavanbecker** [comment]
You will need to be running Homebridge for this plugin to be supported, since HOOBS is still using an older ported and changed version of homebridge.

[How-to-migrate-from-HOOBS-to-Homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-to-migrate-from-HOOBS-to-Homebridge).

If you need any help with this you can reach out on discord.

**Comment by 00JohnD** [comment]
Thank you very much!

**Comment by donavanbecker** [comment]
@00JohnD what are you running HOOBs on?

**Comment by 00JohnD** [comment]
I'm running it on a Raspberry PI 3B+, I've looked at the instruction, I think the migration to homebridge should be easy.

**Comment by donavanbecker** [comment]
Yeah! Let me know if you need any more help.

May I ask, what device are you going to connect?
Also are you using the homebridge-honeywell-home plugin? or are you using the homebridge-honeywell-leak plugin?

**Comment by 00JohnD** [comment]
I'll be using Honeywell leak only with Sensibo, Lifx, Smartthings (for my Zigbee line in thermostats) and TP Link Kasa plugins! Currently they all work fine on Hoobs except the Honeywell one, but I knew I had to upgrade to the newest homebridge one day, so here I am!

Thank you!

**Comment by donavanbecker** [comment]
> I'll be using Honeywell leak only with Sensibo, Lifx, Smartthings (for my Zigbee line in thermostats) and TP Link Kasa plugins! Currently they all work fine on Hoobs except the Honeywell one, but I knew I had to upgrade to the newest homebridge one day, so here I am!
> 
> 
> 
> Thank you! 

You can continue to use the homebridge-honeywell-leak or use homebridge-Honeywell-home which works for Honeywell leak sensors and thermostats.

I manage both plugins.
