### ISSUE TITLE
Set Away Mode?

### ISSUE THREAD

**Issue by Vortec4800** [homebridge-plugins/homebridge-resideo#266]
Does this plugin support setting the away state? I'd basically like a switch or something that can turn away mode on or off based on other factors in the home. Is this possible with their API, and does your plugin support something like that?

**Comment by donavanbecker** [comment]
> Does this plugin support setting the away state? I'd basically like a switch or something that can turn away mode on or off based on other factors in the home. Is this possible with their API, and does your plugin support something like that?

Are you talking about like geofence? Also when you say away mode? Are you talking about changing the temperature when going outside of your house geofence? If so that is something that you can set with the home app through automations.

**Comment by Vortec4800** [comment]
Yes like geofence, but I have a HomeKit alarm system so instead of using location I'd like to make an automation that sets away mode when armed away, and resets back to home mode when disarmed.

**Comment by donavanbecker** [comment]
I don't have alarms setup with this plugin yet. 
I also want to keep this plugin as if the Honeywell devices have HomeKit built in.
so adding a separate switch for automations, is something that I won't add.
Sorry.

**Comment by EthanMendel** [comment]
I'm interested in setting Resideo Home/Away modes/temperatures through Homekit geofencing instead of Resideo's to minimize the number of apps tracking precise location

Does this plugin support that use case?

**Comment by donavanbecker** [comment]
you can't set the mode, but you can set automations up in the home app and that would change the temperature based off that.

**Comment by EthanMendel** [comment]
Yes I know that.. but setting a manual temperature in the home app means I have to forgo modes and scheduling within Resideo app all together (also means you would need to set more automations to implement a sleep mode (automations that need to be turned off manually when on vacation))

Additionally, setting a manual temperatures within the Home app requires picking a specific temperature, where using Home/Away/Sleep modes within the Resideo app allows different heating/cooling temps based on weather

I think this would be a very useful enhancement and a major improvement in this plugin

**Comment by donavanbecker** [comment]
how would we set these modes in the Home app?

**Comment by EthanMendel** [comment]
A 'security system' device could be added. The Aqara M1S (and [homebridge-ring](https://github.com/dgreif/ring) plugin) both have support for this kind of security system:
<img width="330" alt="Screenshot 2023-04-20 at 2 39 50 PM" src="https://user-images.githubusercontent.com/46718883/233458454-4eacd0c7-283d-4c87-b02d-aecff10705c1.png">

**Comment by donavanbecker** [comment]
I will accept a PR, but I myself will not add anything to this plugin that is a workaround. Sorry.

**Comment by EthanMendel** [comment]
Can this issue then be re-opened and labeled as an enhancement so that other contributors might consider picking it up?

I'm happy to try and learn how to contribute myself, but have no experience with homebridge plugins or the resideo apis. Is there a 'getting started' page for contributing?

Also willing to donate for investigation/work on this enhancement
