### ISSUE TITLE
Cannot find a user with these credentials

### ISSUE THREAD

**Issue by arrmo** [homebridge-plugins/homebridge-resideo#268]
Hi,

Could be me, but getting this error when trying to link accounts ... but if I use the same credentials (checked 3 times ... LOL), I can log in to the developer site, confirm that the app has been created => it just breaks when trying to link.

Sorry, not sure what logs to really collect, from the Homebridge side, given that the login is failing. Thinking it's URL (for auth) related perhaps? Just let me know, I can grab them! And I will grab them, once I know what will help. Thinking there isn't much right now 😞.

FYI, I also tried a password reset, but I get the same error (no such user exists). Is it not trying to go to https://developer.honeywellhome.com/?

Checked, nothing logged in Homebridge. And this is running in Ubuntu, v20.10.

Thanks!

**Comment by arrmo** [comment]
OK, figured it out - very odd, but the developer web site and api (site) have different logins. Very odd.

Next up, my devices not being seen 😞 

Thanks!

**Comment by c-fitzmaurice** [comment]
@arrmo Do you have a solution to this? I am having the same problem, and can't get a login to work.

**Comment by arrmo** [comment]
Yes - as above, carefully set up your accounts. As noted, "the developer web site and api (site) have different logins.".

**Comment by c-fitzmaurice** [comment]
Thanks for the response @arrmo but I'm sorry I must be missing something. The only login I can find is the developer.Honeywell.com. I cannot find account creation for the api.Honeywell.com

**Comment by arrmo** [comment]
It was this site that I needed to create an account at,
https://developer.honeywellhome.com/

**Comment by PelagicDev** [comment]
@arrmo the developer site (https://developer.honeywellhome.com/) is where you have to create the account so that you can then create the 'app' for the homebridge plugin to work. That said, what is the API site that we need an account for?

I have create accounts for [Honeywell Developer](https://developer.honeywellhome.com/) and [MyTotalComfort/Honeywell Home](https://mytotalconnectcomfort.com/portal/). Neither of those logins work when trying to authenticate this Homebridge plugin.

Tips?

**Comment by arrmo** [comment]
> Neither of those logins work when trying to authenticate this Homebridge plugin.

Are you not able to log in, or not able to connect devices?

**Comment by PelagicDev** [comment]
> > Neither of those logins work when trying to authenticate this Homebridge plugin.
> 
> Are you not able to log in, or not able to connect devices?

I can't login in Homebridge when the separate Honeywell login screen pops up. It just says "can't find a user with these credentials".

**Comment by arrmo** [comment]
Yep, I had that - but setting up the Developer login worked for me. Sorry!

**Comment by c-fitzmaurice** [comment]
Sorry guys, but I feel like I'm missing something.

I have also created "the developer login" at https://developer.honeywellhome.com/ and can log into that site and see my "app" as approved. With all this, I still cannot login in Homebridge and am seeing the "can't find a user with these credentials".

I am having the same problem as @PelagicDev - I have created every honeywell account I can find and none of them are working.

**Comment by PelagicDev** [comment]
> Yep, I had that - but setting up the Developer login worked for me. Sorry!

Okay, fair enough, I don't expect you to solve this for me, but I am confused. Above, you said this:

> It was this site that I needed to create an account at,
> https://developer.honeywellhome.com/

But, if you follow the instructions in the Readme, you would have already had to have created that account in order to create the 'app' for Homebridge to connect to (the site that gives you the Consumer key & secret). But the way you worded your response makes it seem as though you _created it after you already had the Consumer key & secret._ Can you elaborate where you started in the process and confirm what Honeywell sites you created accounts for?

Any help here would be appreciated. Thanks!

**Comment by arrmo** [comment]
Sorry - wasn't meaning to confuse you. I admit, I went through multiple permutations and combinations to get it all working, and created multiple apps (for Homebridge, but also API testing). I did have the app information (key and secret) before connecting to Homebridge, as you note (wasn't trying to imply the other way around - again, sorry for the confusion!).

**Comment by PelagicDev** [comment]
I finally got this all figured out last night. So, for anyone that comes across this in the future:

When you go to 'link your account' within homebridge, the login you want to use is the email/password for the "Honeywell Home" app on your phone. This is not the same login as the API/Developer website, nor is it the same for 'MyTotalConnect'.

To clarify, the two accounts that you'll need for this to work are:
- https://developer.honeywellhome.com/
- Honeywell Home App (create an account from the app, but you probably already have one assuming your thermostat is already setup)

cc @c-fitzmaurice

**Comment by donavanbecker** [comment]
> When you go to 'link your account' within homebridge, the login you want to use is the email/password for the "Honeywell Home" app on your phone. This is not the same login as the API/Developer website, nor is it the same for 'MyTotalConnect'.

@PelagicDev, FYI I do believe you can connect your Total Connect with a Honeywell home account and use the Honeywell home app now also. just figured I would throw that in there.

**Comment by arrmo** [comment]
FYI, not finding that my devices show up when trying to connect ... seems (per Residio developers), that 
```
You can't control your "imported" TCC devices via the Honeywell Home API right now. It is a long list of reasons, mostly technical, some business.
```

**Comment by donavanbecker** [comment]
> FYI, not finding that my devices show up when trying to connect ... seems (per Residio developers), that 
> 
> ```
> 
> You can't control your "imported" TCC devices via the Honeywell Home API right now. It is a long list of reasons, mostly technical, some business.
> 
> ```

@arrmo This is not a log from the Honeywell-home plugin...

**Comment by arrmo** [comment]
Yes, correct! Sorry if I confused you - it's a direct quote from Residio ... seems TCC imported devices can't be accessed from the Honeywell Home API. Just wanted to let you know.

Thanks!

**Comment by donavanbecker** [comment]
@arrmo Have you tried this in the Honeywell home app?

![image](https://user-images.githubusercontent.com/9875439/103464358-b0fe7a80-4cf8-11eb-95ff-d8c56bbc09b8.jpeg)

**Comment by arrmo** [comment]
Yep! I did the import, and I see my thermostats (and can control them) in the Honeywell Home App. But, when I try to connect to it in Homebridge (Link Account) - they don't show up.

Make sense?

Thanks!

**Comment by donavanbecker** [comment]
The [developer.honeywellhome.com](developer.honeywellhome.com) account?

**Comment by arrmo** [comment]
In Homebridge > Plugins > Homebridge Honeywell Home > Settings ... Link Account (to Homebridge Honeywell Home). I can log in, but no devices show up (even though they show up in the Honeywell Home App).

Thanks.

**Comment by arrmo** [comment]
FYI, I just re-checked ... I get, `We found 0 devices.`

**Comment by arrmo** [comment]
FYI, I have been emailing with Residio, and now have an API working for TCC devices (at least the beginnings of it 😆). It is different, but exists! Open a ticket for this, or do you want to email / IM me, take a look at it offline?

Thanks!

**Comment by donavanbecker** [comment]
@arrmo I am on our homebridge discord service if you would want to do that?

**Comment by arrmo** [comment]
Ummm ... I'm not, but I can try to get on there ... LOL!

**Comment by donavanbecker** [comment]
https://discord.gg/mSdBfH5WQr

**Comment by Asim12344** [comment]
> I finally got this all figured out last night. So, for anyone that comes across this in the future:
> 
> When you go to 'link your account' within homebridge, the login you want to use is the email/password for the "Honeywell Home" app on your phone. This is not the same login as the API/Developer website, nor is it the same for 'MyTotalConnect'.
> 
> To clarify, the two accounts that you'll need for this to work are:
> 
> * https://developer.honeywellhome.com/
> * Honeywell Home App (create an account from the app, but you probably already have one assuming your thermostat is already setup)
> 
> cc @c-fitzmaurice

can you plz tell me exact name of app that i have to find on google play store because i could not find the app

**Comment by PelagicDev** [comment]
I don't know for sure because I have iOS, but from a quick search the icon for iOS looks the to be same for this Android app:

https://play.google.com/store/apps/details?id=com.honeywell.android.lyric

**Comment by egrass-git** [comment]
> FYI, not finding that my devices show up when trying to connect ... seems (per Residio developers), that
> 
> ```
> You can't control your "imported" TCC devices via the Honeywell Home API right now. It is a long list of reasons, mostly technical, some business.
> ```

Say, did you ever find out more on TCC device support in the api?  I followed your same path and got everything working until I realized my TCC apparently was not supported.  Cheers.

**Comment by bigbadbabey** [comment]
I am having the same issue. I am able to log into the Resideo App on my phone with the User name and password but get this error when trying to link it to home bridge.

**Comment by donavanbecker** [comment]
@bigbadbabey open new issue. Everyone's setup is different. Take screenshots or video of each step.
