### ISSUE TITLE
Support for Honeywell D6 and heat pump systems

### ISSUE THREAD

**Issue by grahamwilliams** [homebridge-plugins/homebridge-resideo#270]
I’ve attempted to use this with my Honeywell-driven heat pump D6 Thermostat; could we discuss adding support for that device?

**Comment by donavanbecker** [comment]
@grahamwilliams sorry for the late response. Anyway you can reach out to me on homebridge discord server so we can add support for this?

**Comment by grahamwilliams** [comment]
> @grahamwilliams sorry for the late response. Anyway you can reach out to me on homebridge discord server so we can add support for this?

Ack. Apparently I wasn’t getting GitHub emails til now. 

Where can I find the server details?
