### ISSUE TITLE
Certify for HOOBs

### ISSUE THREAD

**Issue by jay9055** [homebridge-plugins/homebridge-resideo#290]
**Is your feature request related to a problem? Please describe.**
When attempting to use the plugin on Hoobs. the "link account" screen does not show

The plugin will install and you can enter the keys and such but it does not link the "link account" box
**Describe the solution you'd like**
Certify the plugin so it works as intended in Hoobs or provide a workaround

![2020-11-18_140258](https://user-images.githubusercontent.com/39777927/99575634-e4828100-29a6-11eb-8af6-93be31dec84b.png)

**Comment by donavanbecker** [comment]
This plugin is made specifically for Honeywell. I would recommending moving from HOOBs to homebridge. If you need help with that the homebridge UI has a backup restore and does work to restore a HOOBs backup.
