### ISSUE TITLE
Can this plugin add automation to t5 thermostat?

### ISSUE THREAD

**Issue by vhm14u2c** [homebridge-plugins/homebridge-resideo#309]
Wasn’t sure if it was implemented,
Where if thermostat heats or cools, can Turn on switch, like fan.  Then when heating or cooling turns off, turn off switch.

I see it can be done via 3rd party app with correct accessories- 

https://www.imore.com/how-create-temperature-based-automation-homekit

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

https://www.imore.com/how-create-temperature-based-automation-homekit

**Additional context**

**Comment by donavanbecker** [comment]
since the home app doesn't have that support, The only way that you would be able to implement this is with a 3rd part app. Which I just look at my own thermostat and it allowed me to set those triggers.
