### ISSUE TITLE
Sensor readout incorrect

### ISSUE THREAD

**Issue by gcmichael** [homebridge-plugins/homebridge-resideo#323]
I have three sensors located in different parts of the house. All three sensors read the same humidity and temperate. The readings are different from the sensors in the Honeywell Home app

**Comment by donavanbecker** [comment]
@gcmichael and @arcticgenes , Thanks to @NorthernMan54. We have refactored the plugin to better catch these things and also assign the right read out for each sensors. Can you test the latest Beta?

**If you have Homebridge UI:**

<img width="709" alt="Screen Shot 2020-12-08 at 6 56 02 PM" src="https://user-images.githubusercontent.com/9875439/101559592-0dcf7500-3987-11eb-8ee3-9eee403cb645.png">
<img width="511" alt="Screen Shot 2020-12-08 at 6 55 53 PM" src="https://user-images.githubusercontent.com/9875439/101559608-13c55600-3987-11eb-872f-25a7ed2695ff.png">
<img width="512" alt="Screen Shot 2020-12-08 at 6 55 46 PM" src="https://user-images.githubusercontent.com/9875439/101559617-1922a080-3987-11eb-9792-d1f5098a5592.png">


**Manually:**
To install:
``` 
sudo npm install -g --unsafe-perm homebridge-honeywell-home@beta
```

To Revert:
``` 
sudo npm install -g --unsafe-perm homebridge-honeywell-home@beta
```

**Comment by arcticgenes** [comment]
installed the beta and it fixed the sensor readings for me.  The rooms now match in homekit and in my honeywell app.

**Comment by donavanbecker** [comment]
@arcticgenes that is awesome! please keep testing for a few days. After all is good and with a little more clean up we will release a new version.

**Comment by gcmichael** [comment]
Just installed it works fine. The room sensors appear as thermostats in the rooms and the readings are correct. 

One issue when I changed from auto to off the thermostat went to the off position and bounced back on and then went off. 

Kind Regards
Gavin
408 966 7144

**Comment by gcmichael** [comment]
Attached is a screen recording. In this case I turned it off and it was fine. Turned it on and you can see the bounce. 



Kind Regards
Gavin

**Comment by MaverickC2** [comment]
Had the same issue as the other users above. Installed the BETA but had to clear all cached accessories before the readouts were corrected. Looks like its working now. Will report back after a few days of monitoring.

**Comment by donavanbecker** [comment]
`v8.2.0` has been released with a fix for this issue! 

Merry Christmas!
