### ISSUE TITLE
Leak Sensor Display Issue

### ISSUE THREAD

**Issue by donavanbecker** [homebridge-plugins/homebridge-resideo#378]
**Describe The Bug:**

If you change the unit of measurement to Celcius, the Temperature reading would be rounded up to 0.5 stop and the humidity would be added +/-1%
But overall, all good

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here. If using Homebridge Config-UI-X, you can easly downlaod your log by visiting the log page on the UI and Clicking the Download Icon in the top right.
Remove any sensitive information, such as your homebridge-honeywell-home refreshToken.

Please Turn on Debug Mode before submitting your Issue so more logs can be shared to fix the issue being submitted.

There is a hidden `"devicediscovery: true"` option that you can add to your config that will output data about your device to your log also.

***Read and Paste over this Text the Text Above^^^^^^
```

**Homebridge Config:**

```json
Paste your homebridge config.json here.
Remove any sensitive information, such as your homebridge-honeywell-home consumerKey/ consumerSecret / refreshToken.

***Read and Paste over this Text the Text Above^^^^^^
```

**Screenshots:**

**Device & Model:**

# **Environment:**

- **Node.js Version**: 
- **NPM Version**: 
- **Homebridge Version**: 
- **Homebridge Honeywell Home Plugin Version**:
- **Homebridge Config UI X Plugin Version**:
- **Operating System**:

**Comment by donavanbecker** [comment]
@jamesngob

Can you test out the latest beta and see if this fixes your issue?

**Comment by jamesngob** [comment]
@donavanbecker I installed the latest beta
Reading seems to be faster.
Change the unit to C, the Honeywell Home app show 4.9 C and the Apple Home app show 5.0 C, pretty close. I just wait for the next refresh cycle and would report back here again...

**Comment by donavanbecker** [comment]
@jamesngob I had the setProps set to `0.5`, changed it to `0.1` and pushed it to Version 9.1.0. 

Let me know if this fixes it.
