### ISSUE TITLE
Cannot Change temperature

### ISSUE THREAD

**Issue by cherk947** [homebridge-plugins/homebridge-resideo#395]
If I have my Homebridge on I cannot change the temperature in the Honeywell Home app.  It changes and then changes back to the previous temp.   I get the same error if I change the temp in Homekit.  

I get the following:

HoneywellHome] Sending request for Family Room Thermostat to Honeywell API. mode: Heat coolSetpoint: 78 heatSetpoint: 66 thermostatSetpointStatus: undefined
[HoneywellHome] "Request failed with status code 400"

If I turn off my Homebridge the app works.  I can change the temp and it stays.

Change temp and you will see the temp change back within 10-20 seconds.

Change and stay via Honeywell App or HomeKit

**Logs:**

```
Show the Homebridge logs here. If using Homebridge Config-UI-X, you can easly downlaod your log by visiting the log page on the UI and Clicking the Download Icon in the top right.
Remove any sensitive information, such as your homebridge-honeywell-home refreshToken.

Please Turn on Debug Mode before submitting your Issue so more logs can be shared to fix the issue being submitted.

There is a hidden `"devicediscovery: true"` option that you can add to your config that will output data about your device to your log also.

***Read and Paste over this Text the Text Above^^^^^^
```

**Homebridge Config:**

```json
Paste your homebridge config.json here.
Remove any sensitive information, such as your homebridge-honeywell-home consumerKey/ consumerSecret / refreshToken.


            "platform": "HoneywellHome",
            "consumerSecret": 
            "consumerKey": "
            "credentials": {
                "consumerKey": 
                "consumerSecret": "
                "accessToken": "
                "refreshToken": "
            }
        }
    ]
}

***Read and Paste over this Text the Text Above^^^^^^
```

**Screenshots:**

**Device & Model:**

# **Environment:**

- **Node.js Version**:  v14.15.4
- **NPM Version**:  v6.14.11
- **Homebridge Version**:  Homebridge v1.3.0-beta.47
- **Homebridge Honeywell Home Plugin Version**: homebridge-honeywell-home v8.3.2
- **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.36.0
- **Operating System**:  Windows

**Comment by donavanbecker** [comment]
@cherk947 Can you fill in the bottom part of the template so know what device you have? Version of your plugin..., etc.

**Comment by cherk947** [comment]
@donavanbecker sorry thought I saved that the first time.  Updated

**Comment by donavanbecker** [comment]
> @donavanbecker sorry thought I saved that the first time.  Updated

Thanks, What about device? Which device are you using?

**Comment by cherk947** [comment]
I have three Honeywell T9 with Sensors.

**Comment by donavanbecker** [comment]
Awesome! Can you provide debug logs?

**Comment by cherk947** [comment]
[homebridge.log-2.txt](https://github.com/donavanbecker/homebridge-honeywell-home/files/5861375/homebridge.log-2.txt)

Not seeing the failure this evening.  Will continue to monitor and will pass logs once the failure occurs again.  You should see the previous events earlier in the logs

**Comment by cherk947** [comment]
@donavanbecker I did some more testing this evening.  I found that if I turn off my Homebridge or unlink the plugin the Honeywell app works fine.  As soon as I turn on my Homebridge or re-link the app my issue with changing the temp in the Honeywell App or via HomeKit does not set.  It resets in a few seconds.  In the Honeywell App I see the temp go to zero for a second or two then resets back to the previous temperature setting.

**Comment by cherk947** [comment]
Looks like everything is working. Updated my UI to the latest.  Don't think that has anything to do with it but... you never know

**Comment by donavanbecker** [comment]
Awesome

**Comment by AbeltjeNL** [comment]
Same issue here since I've updated to 8.4.0. 
8.3.2 works fine. I'm only using HomeKit, not the Honeywell app. Lyric T6.

@donavanbecker.

**Comment by yonigold1** [comment]
Same issue here on Lyric T5 (i will change the temp on the plugins thermostat and then on the native thermostat in homekit i won't see the temp change)

**Comment by cherk947** [comment]
One thing I tired that has seemed to be successful is to unlink the account in HB and then delete the app on the Honeywell portal.  Create a new one.  This has worked for me

**Comment by AbeltjeNL** [comment]
> One thing I tired that has seemed to be successful is to unlink the account in HB and then delete the app on the Honeywell portal.  Create a new one.  This has worked for me 

Didn't work for me.

**Comment by donavanbecker** [comment]
If you are having issues. Each person Please open a new issue so I can get info about your setup to get this resolved.

**Comment by cherk947** [comment]
Updated to homebridge-honeywell-home v8.4.0 and we are broken again.  :(

**Comment by donavanbecker** [comment]
@cherk947 not really sure what to tell you. I didn't really change much with T9 if you want to compare https://github.com/donavanbecker/homebridge-honeywell-home/compare/v8.3.2...v8.4.0

**Comment by donavanbecker** [comment]
![image](https://user-images.githubusercontent.com/9875439/107467419-999e8280-6b2b-11eb-9237-0c7dbd03ffdc.jpeg)

It might be a Honeywell Server thing. I am going to close this. If it happens tomorrow please open a new issue.

**Comment by donavanbecker** [comment]
@cherk947 what Is your Devices Units? Fahrenheit or Celsius

**Comment by bramsmulders** [comment]
@donavanbecker where does that screenshot come from? I'm experiencing problems as well with my Honeywell thermostat. 
I cannot alter the temperature from homekit or the homebridge-UI. It just jumps back to its original state. 
When I change the temperature via the honeywell app the thermostat will update to the desired temperature and starts heating. After a while the correct temperature is updated in the home.app and the homebridge UI as well. So polling the current state works, but updating the temperature through homekit/homebridge returns a `Request failed with status code 400`.

**Comment by donavanbecker** [comment]
@bramsmulders Please open your own issue to track your issue.

**Comment by cherk947** [comment]
@donavanbecker  Yes in Fahrenheit and it is still not working.  I dont even see the attempt in the logs when I change the temp via the Honeywell app or HomeKit

**Comment by cherk947** [comment]
Issue is still occurring today.

**Comment by donavanbecker** [comment]
Please revert to 8.3.2 till I get a fix out.

**Comment by cherk947** [comment]
Thanks @donavanbecker   It looks to be working.  Thanks again for all your hard work on this plugin

**Comment by donavanbecker** [comment]
@cherk947 I am going to work on a big overhaul on the plugin so might take a little bit. I will need beta testers and will post it in the issues when ready.

**Comment by cherk947** [comment]
Always be glad to beta test!

**Comment by donavanbecker** [comment]
@cherk947 @bramsmulders @yonigold1 @AbeltjeNL 

Please see #414.
