### ISSUE TITLE
is TH8321R1001 RedLink internet gateway supported?

### ISSUE THREAD

**Issue by dkossman** [homebridge-plugins/homebridge-resideo#400]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hello,

I have two Honeywell VisionPro RedLink thermostats, model TH8321R1001. I plan to purchase a THM6000R7001 Redlink/internet gateway, which apparently will allow me to control these via the Honeywell Home app.

Can you clarify whether I would then be able to use this plugin to control these thermostats?

thanks
**Describe alternatives you've considered**

**Additional context**

**Comment by donavanbecker** [comment]
If you can access them in the Honeywell home app, I would assume you can use it wit the plugin. Without testing it, I can't say for sure.
