### ISSUE TITLE
v9.0.0 Beta - T5 Testers

### ISSUE THREAD

**Issue by bramsmulders** [homebridge-plugins/homebridge-resideo#412]
**Describe The Bug:**

I'm experiencing problems since this pas night (02:00 GMT+1) with homebridge & my Honeywell thermostat.
I cannot alter the temperature from homekit or the homebridge-UI. After a couple of seconds the temperature just jumps back to its original state. In the homebridge logs there are errors logged:
```
[10/02/2021, 15:22:48] [HoneywellHome] Sending request for Thermostat Thermostat to Honeywell API. mode: Off coolSetpoint: 10 heatSetpoint: 21.5 thermostatSetpointStatus: PermanentHold
[10/02/2021, 15:22:49] [HoneywellHome] "Request failed with status code 400"
```

When I change the temperature via the honeywell app the thermostat will update to the desired temperature and starts heating. After a while the correct temperature is updated in the home.app and the homebridge UI as well. So polling the current state works, but updating the temperature through homekit/homebridge returns a Request failed with status code 400.

**To Reproduce:**

Outlined above.

**Expected behavior:**

Updating the thermostat via home.app just needs to work. 😉

**Logs:**

When changing the temperature or change the `mode`.
```
[10/02/2021, 15:22:48] [HoneywellHome] Sending request for Thermostat Thermostat to Honeywell API. mode: Off coolSetpoint: 10 heatSetpoint: 21.5 thermostatSetpointStatus: PermanentHold
[10/02/2021, 15:22:49] [HoneywellHome] "Request failed with status code 400"
```

And what occured around 2:00 tonight:
```
[10/02/2021, 02:03:07] [HoneywellHome] Failed to refresh access token. "getaddrinfo ENOTFOUND api.honeywell.com"
[10/02/2021, 02:03:27] [HoneywellHome] T5 - Failed to update status of Thermostat "getaddrinfo ENOTFOUND api.honeywell.com" undefined
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "",
        "username": "",
        "port":,
        "pin": ""
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port":,
            "platform": "config"
        },
        {
            "name": "HoneywellHome",
            "credentials": {
                "consumerKey": "",
                "consumerSecret": "",
                "refreshToken": "",
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "thermostat": {
                    "thermostatSetpointStatus": "PermanentHold"
                },
                "roompriority": {
                    "priorityType": "PickARoom"
                }
            },
            "platform": "HoneywellHome"
        }
    ]
}
```

**Device & Model:**

T5

# **Environment:**

- **Node.js Version**: v14.15.4
- **NPM Version**: v6.14.10
- **Homebridge Version**: v1.1.7
- **Homebridge Honeywell Home Plugin Version**: v8.4.0
- **Homebridge Config UI X Plugin Version**: v4.38.0
- **Operating System**: Raspbian

**Comment by donavanbecker** [comment]
@bramsmulders if you switch back to v8.3.2 do those errors go away?

**Comment by donavanbecker** [comment]
Please see #414.

**Comment by bramsmulders** [comment]
I've switched back to 8.3.2, relinked the honeywell developer app and all started working again.

**Comment by donavanbecker** [comment]
@bramsmulders what logs are you getting with the Beta?

**Comment by donavanbecker** [comment]
@bramsmulders can you try the latest beta: `8.5.1-beta.2`

**Comment by bramsmulders** [comment]
I'm gonna give it a try now!

**Comment by bramsmulders** [comment]
Seems to work with `8.5.1-beta.3` 👍🏼
