### ISSUE TITLE
v9.0.0 Beta Testers Needed - All Thermostat Model Testing Needed.

### ISSUE THREAD

**Issue by donavanbecker** [homebridge-plugins/homebridge-resideo#414]
## Beta Testing v9.0.0

I have combined all thermostat files into 1 file. This means that all Thermostat Models will create a Thermostat Device, I need to keep track of all devices that have been tested and if they are working properly. I will update below to keep track, please comment if you have tried a different model then below and if it is working or if you are having issues.

Also Please open your own issue on GitHub so that we can track each model and get logs from your setup.

NPM: `v9.0.0` will show as `v8.5.1-beta.x`

### Thermostat Models Tested

- T9: Currently working with `v8.5.1-beta.0`.
- T6: Last Tested `8.5.1-beta.3`.
- T5: Last Tested `8.5.1-beta.3`.
- Round:
- TCC (Unknown):

### Other Devices Tested

- LeakSensor: Currently working with `v8.5.1-beta.0`.

**Comment by AbeltjeNL** [comment]
T6: 
Working with: V8.3.2
Not working with: V8.4.0 & V8.5.1beta

**Comment by donavanbecker** [comment]
> T6

@AbeltjeNL Can you open an issue to track T6?

**Comment by bramsmulders** [comment]
T5: working with v8.3.2, not working with v8.4.0

**Comment by AbeltjeNL** [comment]
> > T6
> 
> @AbeltjeNL Can you open an issue to track T6?

Done!

**Comment by cherk947** [comment]
T9 with  v8.5.1-beta.0 not working. 9.0 not an option in HB.

**Comment by donavanbecker** [comment]
@cherk947
> T9

Can you open a issue?

**Comment by wtadler** [comment]
Thermostat-TCC-2728972-Round [Not sure if this is a TCC or a Round...]

Not working in 8.3.2, 8.4.0, or 8.5.1-beta.0. Can't get 9.0 through npm.

**Comment by donavanbecker** [comment]
@wtadler 
> Thermostat-TCC-2728972-Round [Not sure if this is a TCC or a Round...]
> Not working in 8.3.2, 8.4.0, or 8.5.1-beta.0. Can't get 9.0 through npm.

@cherk947
> T9 with v8.5.1-beta.0 not working. 9.0 not an option in HB.

NPM: `v9.0.0` will show as `v8.5.1-beta.x`

**Comment by cherk947** [comment]
@donavanbecker installed homebridge-honeywell-home v8.5.1-beta.3 and we are back in business

**Comment by yonigold1** [comment]
hey I can help test v9.0.0 I have a T5 thermostat 
If you would like of course :)

**Comment by donavanbecker** [comment]
@yonigold1 yes if you can install the latest beta available which would be v8.5.1-beta.7, and let me know if you run into any issues.

**Comment by cherk947** [comment]
@donavanbecker v8.5.1-beta.11 is working well with the T9.  Can change the temp in Honeywell app and HomeKit and see the appropriate update in HB
