### ISSUE TITLE
Can't control devices

### ISSUE THREAD

**Issue by iRayanKhan** [homebridge-plugins/homebridge-resideo#50]
Hi there,

Every day it seems like the access and refresh tokens refresh and I have to generate a new one constantly, is this a known issue, or am I doing something wrong?

**Comment by donavanbecker** [comment]
What version do you have?

**Comment by iRayanKhan** [comment]
I am using V4.0.2

**Comment by donavanbecker** [comment]
are you using config-ui-x?

**Comment by iRayanKhan** [comment]
Nope, I did the manual way. 
I may try config-ui-x, but do I need to define that plugin in all of my home bridge instances?

**Comment by donavanbecker** [comment]
You should only need it for one instance. Can you post your config?

Also config UI x is way easier.

**Comment by iRayanKhan** [comment]
Sure here is my config:
```json
{
        "bridge": {
                "name": "Thermostat Bridge",
                "username": "CC:22:2D:E3:CE:20",
                "port": 51867,
                "pin": "031-45-450"
        },

     
        "ports": {
                "start": 52100,
                "end": 52150,
                "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
        },

        "platforms": [{
                "platform": "homebridge-honeywell-home.HoneywellHome",
                "name": "HoneywellHome",
                "credentials": {
                        "consumerKey": " ",
                        "consumerSecret": " ",
                        "accessToken": " ",
                        "refreshToken": " "
                },
                "options": {
                        "ttl": 60,
                        "verboseP": false
                }
        }]
}

```
Edit just noticed I pasted the wrong config from a different Pi, I just tried out homebridge-config-ui-x and it's good so far. I am on my Mac so I can't re-add the bridge to my Home just yet.

**Comment by donavanbecker** [comment]
If you are running this plugin on two instances that is probably the problem, because the refresh token doesn't know which one to use. Also Config UI X makes it the easiest so I would continue to use that. I haven't had an issue with it not working since 4.0.0 has came out.

**Comment by donavanbecker** [comment]
@iRayanKhan: `v7.0.1` should take care of all the issues, if not I need a new issue filled out so I can look into it further. Please follow issue template so that I can get all the details I need. When posting logs, debug mode will be needs to look into further issues.
